version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./credentials.json:/app/credentials.json:ro
      - ./tmp:/app/tmp
    env_file:
      - .env
    environment:
      - GOOGLE_CREDENTIALS_FILE=credentials.json
      - LOG_LEVEL=INFO
    restart: unless-stopped
    command: ["python", "main.py"]
# TODO: Application starts immediately after build,
# we should add a management command or UI to start the application
